var adMiejsce=[];
var adBlockTest=true;
(function(){var h=["Reklama","Nasi partnerzy"],k=document,g="%3Cscript%20type%3D%22text%2Fjavascript%22%3E",e="%3C%2Fscript%3E",f,c=oG_OSA&&oG_OSA.trybReklamy||"old",a,b,j,l;
function i(){var d="abcdefghijklmnopqrstuvwxyz",n=[],m;
d+=d.toUpperCase();
for(m=0;
m<10;
m+=1){n.push(d.charAt((Math.floor(Math.random()*10)+0)))}return n.join("")}f=function(){var m;
if("undefined"==typeof ado){return}ado.config({mode:c,xml:"false",characterEncoding:"true",protocol:location.protocol});
ado.preview({enabled:true,emiter:oG_OSA.adOceanEmiter,id:oG_OSA.adOceanPreviewId});
function n(q,w){var y=q.parentNode,v=(y.tagName.toUpperCase()==="TD"),s=["OBJECT","IFRAME","A","IMG","TABLE"],x=s.length,r,u,p=null,t=15,A=0,z=250;
p=setInterval(function(){for(u=0;
u<x;
u+=1){r=!!(y.getElementsByTagName(s[u])[0]);
if(r){break}}A+=1;
if(r){if(v){y.style.display="";
y.parentNode.style.display=GR("czyIE")?"block":"table-row"}else{y.style.display="block"}A=0;
clearInterval(p);
return}y.style.display="none";
if(v){y.parentNode.style.display="none"}if(A>t){clearInterval(p);
if("function"===typeof w){w()}}},z)}function o(p){var s=adMiejsce[p.nazwa],r={myMaster:m,onLoad:"function"===typeof p.onLoad?p.onLoad:null};
if(!s){return}r.onServerEmission=function(){var t=$(this.id),u;
if(!t){return}u=t.parentNode;
if(p.tytul||(p.tytulWRodzicu&&u.children[0].className!=="adTytul")){GR("utworzElement",(!p.tytulWRodzicu?t:u),"span",{"class":"adTytul"},"pierwszy",p.tytul)}t.style.display="block";
if(p.nazwa==="billboard"||p.pokazUkryjRodzica){n(t,p.onServerEmissionEmpty)}if("function"===typeof p.onServerEmission){p.onServerEmission.call(this)}};
r.onServerEmissionEmpty=function(){var t=$(this.id),u;
if(!t){return}u=t.parentNode;
if(p.tytul&&p.tytulWRodzicu&&u.children[0].className!=="adTytul"&&!p.pokazUkryjRodzica){GR("utworzElement",u,"span",{"class":"adTytul"},"pierwszy",p.tytul)}if(p.nazwa==="billboard"||p.pokazUkryjRodzica){if(u.tagName.toUpperCase()==="TD"){u.parentNode.style.display="none"}u.style.display="none"}if("function"===typeof p.onServerEmissionEmpty){p.onServerEmissionEmpty.call(this)}};
try{if(GR("czyReklama",p.nazwa)){if(p.tag!=="pusty"){if(typeof p.rodzic=="undefined"){k.write("<"+p.tag+' id="'+s+'"'+(p.cssClass?' class="'+p.cssClass+'"':"")+(p.cssStyle?' style="'+p.cssStyle+'"':"")+">");
if("old"===c){ado.slave(s,r)}k.write("</"+p.tag+">")}else{jQuery("<"+p.tag+' id="'+s+'"'+(p.cssClass?' class="'+p.cssClass+'"':"")+(p.cssStyle?' style="'+p.cssStyle+'"':"")+"></"+p.tag+">").appendTo(jQuery(p.rodzic))}}if("new"===c){ado.slave(s,r)}return}}catch(q){}}function d(q,t,p){m=q;
var s,r=[];
for(s=0;
s<t.length;
s+=1){r=r.concat(t[s].split(","))}if(typeof gemius_id!="undefined"){p.cid=""+gemius_id}ado.master({id:q,server:oG_OSA.adOceanEmiter,keys:r,vars:p})}return{wpisz:o,inicjalizujMaster:d,kodMaster:m,pokazUkryjRodzica:n}}();
cGR.prototype.czyReklama=function(d){return(adMiejsce&&adMiejsce[d]?1:0)};
cGR.prototype.pokazReklameOdSzerokosci=function(n){var m=!!ado,q=jQuery(n.rodzic),o=n.szerokosc,p=typeof n.szerokoscMax!="undefined"?n.szerokoscMax:false,d=typeof n.mierzOkno=="undefined"||n.mierzOkno==false?q.width():jQuery(window).width();
if(d>=o&&(!p||d<=p)){if(!q.children().not("script").length){f.wpisz(n)}else{q.children().show()}}else{q.children().hide()}};
cGR.prototype.wstawReklame=function(m,A,u,d,r,B,q){var x=arguments,z=x.length,o,p=["nazwa","cssClass","cssStyle","tytul","pokazUkryjRodzica","tag","onServerEmissionEmpty","onLoad","onServerEmission","tytulWRodzicu"],t=!!ado,s={},v=false,w=false,y;
if(x.length===1&&"object"===typeof x[0]){s=x[0]}else{for(o=0;
o<z;
o+=1){s[p[o]]=x[o]}}if(!s.tag){s.tag="div"}if(s.tytul&&"string"!==typeof s.tytul){s.tytul=h[s.tytul]||""}if(x.length===1&&"object"===typeof x[0]){m=s.nazwa;
A=s.cssClass;
u=s.cssStyle;
d=s.tytul;
r=s.pokazUkryjRodzica;
B=s.tag;
q=s.onLoad;
v=s.szerokosc;
w=jQuery(s.rodzic)}if(w&&v&&t&&!s.old){jQuery(window).resize(function(){clearTimeout(y);
y=setTimeout(function(){GR("pokazReklameOdSzerokosci",s)},200)});
GR("pokazReklameOdSzerokosci",s)}else{if(t&&!s.old){f.wpisz(s)}else{GR("wstawStaraReklama",m,A,u,d,r,B,q)}}};
cGR.prototype.wstawStaraReklama=function(t,m,s,o,r,d,p){r=r||0;
d=d||"div";
try{o=typeof o==="string"?o:h[o]||"";
if(GR("czyReklama",t)){if(d!=="pusty"){k.write("<"+d+' id="ad-'+t+'"'+(m?' class="'+m+'"':"")+(s?' style="'+s+'"':"")+">");
if(o){k.write('<span class="adTytul">'+o+"</span>")}}k.write(unescape(g)+"if (typeof "+adMiejsce[t]+' === "function") {'+adMiejsce[t]+"();
 }"+unescape(e));
if(d!=="pusty"){k.write("</"+d+">")}if("billboard"===t||r){f.pokazUkryjRodzica($("ad-"+t),p)}return}if("function"===typeof p){p()}}catch(q){}};
cGR.prototype.wstawReklameButtony=function(o,p,m){var d=0,n;
o=typeof o==="string"?o:h[o];
for(n=0;
n<p.length;
n+=1){if(GR("czyReklama",p[n])){if(d===0){k.write('<div class="adBoks'+(m?" "+m:"")+'">');
d+=1}GR("wstawReklame",{nazwa:p[n],tytul:o,tytulWRodzicu:true})}}if(d===1){k.write("</div>")}};
cGR.prototype.wstawReklameTextBox=function(o,m,v,w){var p=0,q,t,r=[],n,d=0,s,u=["adTekstPion","adTekstPoziom"];
w=w||null;
o=typeof o==="string"?o:u[o];
v=v||747;
for(q=0;
q<m.length;
q+=1){if(GR("czyReklama",m[q])){if(p===0){k.write('<div class="'+o+(w?" "+w:"")+'"'+(v!==747&&v!=="nf"?' style="width: '+v+'px;
"':"")+">")}r[q]="ad-"+m[q];
GR("wstawReklame",{nazwa:m[q]});
p+=1}}if(p>0){k.write('<span class="tytulik">Reklama</span>');
k.write("</div>")}if(p<4&&p!==0&&o.indexOf("adTekstPion")===-1){n=r.length;
d=n<3?Math.floor(v/2):Math.floor(v/n);
s=n<2?Math.floor((v-(d*n))/2):0;
for(q=0;
q<n;
q+=1){t=$(r[q]);
if(!t){continue}t.style.width=d+"px";
if(s){t.style.marginLeft=(!GR("czyIE")?s:Math.floor(s/2))+"px";
t.getElementsByTagName("a")[0].style.textAlign="center"}}}return(v=undefined)};
cGR.prototype.wstawSkyscraper=function(s,q){var r=["skyscraper-lewy","skyscraper-prawy"],d=0,m,o="";
try{function n(){setTimeout(function(){GR("ustawSkyscraper",s,(parseInt(q,10)||0))},100)}for(m=0;
m<r.length;
m+=1){if(GR("czyReklama",r[m])){GR("wstawReklame",{nazwa:r[m],old:true});
if(!d){d=1;
GR("dodajOnload",n)}}}}catch(p){}};
cGR.prototype.ustawSkyscraper=function(o,n){var m=$("ad-skyscraper-lewy"),d=$("ad-skyscraper-prawy");
if(m||d){if(GR("czyIE")){n=parseInt(n,10)+70}GR("pokazSkyscraper",o,n);
Zdarzenia.zaczep(window,"resize",function(){GR("pokazSkyscraper",o,n)})}};
cGR.prototype.rozmiarSkyscraper=function(n){var d,p,s=0,t=0,m,q,o,r=["a","object","iframe"];
for(d=0;
d<r.length;
d+=1){q=n.getElementsByTagName(r[d]);
o=q.length;
if(o>0){if(d===0){m=new Image();
if(q[0].childNodes[0].width===0){m.src=q[0].childNodes[0].src;
s=parseInt(m.width,10);
t=parseInt(m.height,10)}else{s=parseInt(q[0].childNodes[0].width,10);
t=parseInt(q[0].childNodes[0].height,10)}}else{s=parseInt(q[0].width,10);
t=parseInt(q[0].height,10)}break}}return[s,t]};
cGR.prototype.pokazSkyscraper=function(n,v){var o,r,s=[0,0],w=[0,0],p=$(n),y=$("ad-skyscraper-lewy"),u=$("ad-skyscraper-prawy"),q=$("ad-skyscraper"),m=k.body.clientWidth,d=0,t,x;
if(m&&(y||u)){t=k.getElementsByTagName("body")[0];
if(y){s=GR("rozmiarSkyscraper",y)}if(u){w=GR("rozmiarSkyscraper",u)}x=(parseInt(s[0],10)+parseInt(w[0],10));
d=parseInt((p.width||p.offsetWidth),10);
v=parseInt(v,10)||0;
if((m-d)/2>x){if(u){GR("ustawReguleCss",q,"top: "+(p.offsetTop+v)+"px;
 left: "+(Math.floor((m-d)/2)+d+10)+"px;
 display: block;
")}}else{if(y){q.style.display="none"}if(u){q.style.display="none"}}}};
cGR.prototype.wywolajReklamy=function(m,n,s){if(!m){return}a=n;
kodMaster=n.kodMaster;
try{var d=[],p,q=[],t=0,o=false;
if(1===m){if("string"===typeof n){d[m]=location.protocol+"//"+oG_OSA.adOceanEmiter+"/_"+(new Date()).getTime()+"/ad.js?id="+n+"/x="+screen.width+"/y="+screen.height}else{if(typeof n.minSzerokosc!="undefined"&&jQuery(window).width()<n.minSzerokosc){jQuery(window).resize(function(){clearTimeout(t);
t=setTimeout(function(){if(!o&&jQuery(window).width()>=n.minSzerokosc){f.inicjalizujMaster(n.kodMaster,n.keys,n.vars);
o=true}},200)})}else{f.inicjalizujMaster(n.kodMaster,n.keys,n.vars)}}}else{d[m]=n}for(p in d){if(typeof d[p]==="string"){GR("zaladujPlikJS",d[p],"plik",s)}}}catch(r){}};
cGR.prototype.iframeReklama=function(p,m){var n,o=0,d=[];
p=p||{};
m=m||{};
if(!p.url){p.url=location.protocol+"//"+location.host+"/"}if(!p.miejsce){p.miejsce="button_NxN1"}if(!m.id){m.id="ad-iframe-"+p.miejsce}if(a.vars){o=1;
d[0]="";
for(n in a.vars){if("function"!==a.vars[n]){d[o]=n+"="+a.vars[n];
o+=1}}}m.src=oG_OSA.iframeReklama+"?id="+encodeURI(a.kodMaster+"/key="+a.keys.join(",")+",galeria"+d.join("/")+"&"+adMiejsce[p.miejsce]);
GR("utworzIframe",p.cel,m)};
cGR.prototype.iframeReklamaZaladuj=function(){var d=decodeURIComponent(location.search).split("&");
this.wywolajReklamy(1,d[0].replace("?id=",""))};
cGR.prototype.iframkaReklamaWstaw=function(){var d=decodeURI(location.search).split("&");
k.write(unescape(g)+"if (typeof "+d[1]+' === "function") {'+d[1]+"();
 }"+unescape(e));
GR("dodajOnload",function(){var p=$("reklama-ramka"),r=p.offsetHeight,o=p.getElementsByTagName("object")[0]||p.getElementsByTagName("img")[0],q=p.getElementsByTagName("embed")[0],s=o.height||o.offsetHeight||q.offsetHeight,n=Math.floor((r-s)/2);
if(n<0){n=0}if(o&&s){o.style.marginTop=n+"px";
if(q){q.style.marginTop=n+"px"}GR("usunCssClass",p,"schowaj")}})};
cGR.prototype.ustawReklame=function(u,o){u=$(u);
if(!u||!o){return}if("string"===typeof o){o=o.split(",")}var p=GR("czyIE")?765:755,m=$(o),t=m.length,w,x=[],n=[],r,v,q,d,y;
function s(){var z=u.offsetWidth;
for(q=0;
q<t;
q+=1){w=null;
v=null;
y="";
if(!m[q]){continue}w=m[q].parentNode;
if(m[q].getElementsByTagName("script")[0]){w.style.display="";
w.parentNode.style.display=GR("czyIE")?"block":"table-row"}r=w.getElementsByTagName("object")[0]||w.getElementsByTagName("img")[0]||w.getElementsByTagName("iframe")[0];
if(!r&&!oG_OSA.debug){w.style.display="none";
w.parentNode.style.display="none";
continue}y=r.tagName.toUpperCase();
if(!GR("czyIE")&&y==="OBJECT"){v=w.getElementsByTagName("embed")[0]}if(!n[q]){n[q]=r.height||(v?v.height:0);
x[q]=r.width||(v?v.width:0)}if(z<p){m[q].style.width=(z-40)+"px";
r.height=18;
r.style.height="18px";
if(v){v.height=18;
v.style.height="18px"}}else{m[q].style.width="750px";
r.height=n[q];
r.style.height=n[q]+"px";
if(v){v.height=n[q];
v.style.height=n[q]+"px"}}}}GR("dodajOnload",s);
window.onresize=function(){clearTimeout(d);
d=setTimeout(s,150)}};
cGR.prototype.setScriptAd=function(m){var d=i();
k.write('<div id="'+d+'"></div>');
setTimeout(function(){GR("utworzElement",$(d),"script",{type:"text/javascript",src:m.src,id:m.id||""})},10)};
cGR.prototype.inicjalizujSmartAdserver=function(d){b=Math.round(Math.random()*10000000000);
j=1;
l=d||"";
window.sascc=function(n,m){img=new Image();
img.src="http://www6.smartadserver.com/h/mcp?imgid="+n+"&pgid="+m+"&uid=[uid]&tmstp="+b+"&tgt=[targeting]"}};
cGR.prototype.wstawReklameSmartAdserver=function(m,d){if(GR("czyReklama",m)){dane=adMiejsce[m].match(/(.+\/.+)\/(.+)/)}else{return}sas_formatid=dane[2];
sas_pageid=dane[1];
if(j==1){j=0;
sas_master="M"}else{sas_master="S"}if(typeof d=="undefined"||jQuery(d).is(":visible")){document.write('<script src="http://www6.smartadserver.com/call2/pubmj/'+sas_pageid+"/"+sas_formatid+"/"+sas_master+"/"+b+"/"+escape(l)+'?"><\/script>')}}})();

